language: c
compiler: gcc
dist: bionic

before_install:
  - sudo apt-get install -y python3-pip python3-psutil libc6-dbg
  - sudo -H pip3 install lit
addons:
  apt:
    update: true

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - make smoketests
  - make tests
