function(sabre_add_component target_name)
  add_library(${target_name} STATIC ${ARGN})
  target_include_directories(${target_name} PUBLIC ${SABRE_COMPONENT_INCLUDE_DIRS})
  target_compile_definitions(${target_name} PUBLIC ${SABRE_COMPONENT_C_DEFINES})
  target_compile_options(${target_name} PUBLIC ${SABRE_COMPONENT_C_FLAGS})
endfunction()

function(sabre_add_main_executable)
  add_executable(sabre ${ARGN})
  target_compile_options(sabre PRIVATE "-std=gnu99" "-Wall" "-Wextra" "-Werror" "-fPIE" "-fstack-protector" "-rdynamic")
  set_target_properties(sabre PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
  target_compile_definitions(sabre PUBLIC ${SABRE_COMPONENT_C_DEFINES})
  target_link_libraries(sabre loader)
endfunction()

function(sabre_add_plugin plugin_name)
  add_library(${plugin_name} MODULE ${ARGN})
  target_include_directories(${plugin_name} PUBLIC ${SABRE_PLUGIN_INCLUDE_DIRS})
  target_compile_definitions(${plugin_name} PUBLIC ${SABRE_PLUGIN_C_DEFINES})
  target_compile_options(${plugin_name} PUBLIC ${SABRE_PLUGIN_C_FLAGS})
  target_link_libraries(${plugin_name} ${CMAKE_SYSTEM_PROCESSOR})
endfunction()
